#This script is used to analyze the correlation/covariance of the rates and times in a phylogenetic tree

#read log file that contains rates and times to show the correlationships
#the "p.log" and "q.log" file is generated by "TreeStat2"
P <- read.table(file="~/Desktop/P.log",sep="\t", header=T)
Q <- read.table(file="~/Desktop/Q.log",sep="\t", header=T)
#in windows format
#P <- read.table(file="C:/Users/RongZhang/Desktop/p.log",sep="\t", header=T)
#Q <- read.table(file="C:/Users/RongZhang/Desktop/q.log",sep="\t", header=T)

Q <- Q[,-7]
names(Q)<-c("states","r_8","r_9","r_10","r_11","r_12")
A <- P[,1:8]
B <- P[,9:13]
C <- P[,14:19]
A[,9:13] <- Q[,2:6]
A[,14:19] <- C
A[,20:24] <- B

S <- A
  
S1<-S[which(S$Monophyly.AD.==1),]
S2<-S1[which(S1$Monophyly.ADCEKO.==1),]
S3<-S2[which(S2$Monophyly.CE.==1),]
S4<-S3[which(S3$Monophyly.CEK.==1),]
S5<-S4[which(S4$Monophyly.CEKO.==1),]

T <- S5[,-(20:24)]

 T[,14]=t1
 T[,15]=t2
 T[,16]=t3
 T[,17]=t5
 T[,17]=t4
 T[,18]=t5
 T[,19]=t6
names(T)<-c("state","r1","r2","r3","r4","r5","r6","r7","r8","r9","r10","r11","r12","t1","t2","t3","t4","t5","T")
#color compare
library(corrgram)
corrgram(T [,2:18])

#black-and-white compare
library(car) 
pairs(~NodeAge$Age.10+NodeAge$Age.11+NodeAge$Age.12+NodeAge$Age.7+NodeAge$Age.8+NodeAge$Age.9,data=NodeAge)
pairs(~P$Branch.1+P$Branch.2)

#filter the matrix T1
T1<-T1[which(T1$Monophyly.ADK.==1),]

#give the names for columns in "Study"
names(Study)<-c("r_ANDI","r_DIGI","r_KIWI","r_CASS","r_EMU","r_OST","r_RHEA","r_AD","r_ADK","r_CE","r_ADKCE","r_RO","TreeHeight","t_AD","t_ADK","t_ADKCE","t_RO")