#This script is used to get samples from log file that is generated by MCMC
#The samples are obtained within a fixed foot step, i.e. size of M

#read the log file
L <- read.table(file="/Users/rzha419/Desktop/ratites.log", sep="\t", header=T)


# get M samples in log file
# in log file, there 10001 states
#from 101-th state, a sample is obtained after every 100 states
M=matrix(nrow = 100, ncol = 1)
j=1;
for(i in seq(101, 10001, 100)) {
  M[j]=i;
  j=j+1;
}


A=L$BirthRate;
B=L$kappa;
C=L$ucldStdev;

#birthrates
I=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  I[j]=A[i];
  j=j+1;
}
write.table(I,file="/Users/rzha419/Desktop/Bir.txt",col.name=F,row.names=F)

#kappa
K=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  K[j]=B[i];
  j=j+1;
}
write.table(K,file="/Users/rzha419/Desktop/Kap.txt",col.name=F,row.names=F)
#ucld
U=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  U[j]=C[i];
  j=j+1;
}
write.table(U,file="/Users/rzha419/Desktop/Ucld.txt",col.name=F,row.names=F)


#Frequencies
F1=L$freqParameter.1
F2=L$freqParameter.2
F3=L$freqParameter.3
F4=L$freqParameter.4

#(1) save 4 frequency parameters into 4 seperate files
S1=matrix(nrow = 100, ncol = 1)
S2=matrix(nrow = 100, ncol = 1)
S3=matrix(nrow = 100, ncol = 1)
S4=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  S1[j]=F1[i];
  S2[j]=F2[i];
  S3[j]=F3[i];
  S4[j]=F4[i];
  j=j+1;
}
write.table(S1,file="/Users/rzha419/Desktop/Fre1.txt",col.name=F,row.names=F)
write.table(S2,file="/Users/rzha419/Desktop/Fre2.txt",col.name=F,row.names=F)
write.table(S3,file="/Users/rzha419/Desktop/Fre3.txt",col.name=F,row.names=F)
write.table(S4,file="/Users/rzha419/Desktop/Fre4.txt",col.name=F,row.names=F)
#(2) save 4 frequency parameters into one single file
#S=matrix(nrow = 100, ncol = 4)
#j=1;
#for (i in 1:100) {
#S[j,1]=S1[i];
#S[j,2]=S2[i];
#S[j,3]=S3[i];
#S[j,4]=S4[i];
#j=j+1;
#}
S=cbind(S1,S2,S3,S4)
write.table(S,file="/Users/rzha419/Desktop/Freq.txt",col.name=F,row.names=F)

#BranchRates
#save all the rates into one single file
#ncol=number of rates
R=matrix(nrow = 100, ncol = 12)
j=1;
for (i in M) {
    for (k in 1:12) {
    #depends on the position of rates
    R[j,k]=L[i,18+k]
  }
  j=j+1;
}
write.table(R,file="/Users/rzha419/Desktop/Rates.txt",col.name=F,row.names=F)
#get the mean of the rates
R1=L$rate.mean
RatM=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  RatM[j]=R1[i];
  j=j+1;
}
write.table(RatM,file="/Users/rzha419/Desktop/RatM.txt",col.name=F,row.names=F)

#Tree statistics
D=L$Tree.height
E=L$Tree.treeLength

TreH=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  TreH[j]=D[i];
  j=j+1;
}
write.table(TreH,file="/Users/rzha419/Desktop/TreH.txt",col.name=F,row.names=F)

TreL=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  TreL[j]=E[i];
  j=j+1;
}
write.table(TreL,file="/Users/rzha419/Desktop/TreL.txt",col.name=F,row.names=F)
